---
- name: Include variables.
  include_vars: "main.yml"

- name: Define packages.
  set_fact:
    packages: "{{ __packages | list }}"

- name: Define extra packages.
  set_fact:
    packages: "{{ packages | list + packages_extra | list }}"
  when: packages_extra is defined

- name: Update apt-cache
  apt:
    update_cache: yes

- name: Install packages
  apt:
    pkg: "{{ item }}"
    state: 'latest'
  with_items: "{{ packages }}"