---
- name: update apt-cache
  apt:
      update_cache: yes

- name: install aptitude
  apt:
      pkg: 'aptitude'

- name: upgrade the distro
  apt:
      upgrade: yes

- name: install packages
  apt:
      pkg: "{{ item }}"
      state: 'latest'
  with_items:
      - sudo
      - bash-completion
      - python-pycurl
      - htop
      - tree
      - vim
      - curl
      - zip
      - wget
      - mc